spring:
  application:
    name: fgsc-gateway
    admin:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: false
    fetch-registry: true
  instance:
    prefer-ip-address: true
    app-group-name: fgsc
    appname: gateway
    healthcheck:
      enabled: true
zuul:
  host:
    connect-timeout-millis: 60000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 60000
  semaphore:
    max-semaphores: 500
  prefix: /api
  strip-prefix: true
  ribbon:
    eager-load:
      enabled: true
ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 10000
  ReadTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
        thread:
          timeoutInMilliseconds: 40000
